### ISSUE TITLE
Add GitHub copilot provider

### ISSUE THREAD

**Issue by hadley** [tidyverse/elmer#126]
Copying approach from https://github.com/zed-industries/zed/blob/35f2f2aac4837ded29279587092237baea13973d/crates/copilot/src/copilot_chat.rs#L174

**Comment by hadley** [comment]
Some work at https://gist.github.com/hadley/92015bedc9515b4a6dd43ff2c93f2484, but no longer seems worth it.

**Comment by danielinteractive** [comment]
Hi @hadley , just came across this because I was wondering if `ellmer` can also use GitHub Copilot - since I have a subscription there, it could be interesting. So would this work in principle?

**Comment by hadley** [comment]
In principle, I believe so, but it's not clear that it's allowed by the terms of service, so I'm unlikely to implement it.
