### ISSUE TITLE
Support for Entra ID authentication for the Azure provider

### ISSUE THREAD

**Issue by atheriel** [tidyverse/elmer#141]
Right now we only support API keys for the Azure OpenAI Service, but I'm pretty sure from looking at their [Quickstarts](https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart?tabs=command-line%2Ctypescript%2Cpython-new&pivots=programming-language-javascript#microsoft-entra-id) that you can also use OAuth via Entra ID. That might be an easier and more secure option if the user already has Azure credentials available.

**Comment by JamesHWade** [comment]
I don't have access to an Azure OpenAI service that uses Entra ID auth, but my guess is you could pass an Entra ID token that to the `token` parameter. I haven't come back to adding convenience functions for fetching tokens, but those would be a good addition to the make it even easier for users.

**Comment by hadley** [comment]
In that case I'm going to close this issue for now, but I'm certainly happy to reopen if anyone needs more details.
