### ISSUE TITLE
Deploy to shiny failing

### ISSUE THREAD

**Issue by scarpino** [tidyverse/elmer#172]
I'm trying to deploy an app an receiving the following error message. The app runs fine locally. 

Error: Unhandled Exception: child_task=1481640961 child_task_status=failed: Error building image: Error fetching httr2 (1.0.6.9000) source. <GitHubPackage user='r-lib' repo='httr2' private=False> unable to satisfy package: httr2 (1.0.6.9000)
Execution halted

**Comment by hadley** [comment]
Looks like the problem is installing the dev version of httr2. That will naturally resolve itself when we release to CRAN next week.
