### ISSUE TITLE
Can't find package called shinychat when calling live_browser()

### ISSUE THREAD

**Issue by cortinah** [tidyverse/elmer#191]
live_browser() doesn't start because there is no package called shinychat.   I see a shinyChatR on CRAN, but not sure that's what this is meant to call.

thank you

> live_browser(chat)
ℹ The package "shinychat" is required.
✖ Would you like to install it?

1: Yes
2: No

Selection: 1
✔ Loading metadata database ... done
Error:                                                                     
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* shinychat: Can't find package called shinychat

**Comment by timyers** [comment]
Same thing happened to me.  I got passed this error by installing `shinycat` with:

> pak::pak("jcheng5/shinychat")

....which is in the "Getting Started with Elmer" page.

Then I hit another wall with error after calling elmer::live_browser().  See error below.
 
" Warning: Error in <Anonymous>: argument "chat" is missing, with no default
  46: <Anonymous>
  44: server
   7: shiny::runApp
   6: shiny::runGadget
   1: elmer::live_browser
Error in (function (input, output, session)  : 
  argument "chat" is missing, with no default "

Still trying to figure this one out.

I'm really excited and interested in this new package.  Thank you creating it!

**Comment by cortinah** [comment]
> Same thing happened to me. I got passed this error by installing `shinycat` with:
> 
> > pak::pak("jcheng5/shinychat")
> 
> ....which is in the "Getting Started with Elmer" page.
> 
> Then I hit another wall with error after calling elmer::live_browser(). See error below.
> 
> " Warning: Error in : argument "chat" is missing, with no default 46: 44: server 7: shiny::runApp 6: shiny::runGadget 1: elmer::live_browser Error in (function (input, output, session) : argument "chat" is missing, with no default "
> 
> Still trying to figure this one out.
> 
> I'm really excited and interested in this new package. Thank you creating it!

thanks for this, i will install jcheng5/shinychat.
when calling live_browser() make sure you include the name of the chat you created previously,  it should be something such as:

chatname <- chat_openai( model = "gpt-4o-mini",   system_prompt = "You are a friendly but terse assistant.")
live_browser(chatname) 

for example

**Comment by timyers** [comment]
Oh, right.  Thanks for the tips!

**Comment by hadley** [comment]
Thanks for the tips all! We're aiming to release elmer to CRAN very soon, but we're just waiting on some shinychat fixes.
