### ISSUE TITLE
chat_gemini needs echo = "none" otherwise it doesn't capture full response

### ISSUE THREAD

**Issue by leesahanders** [tidyverse/elmer#199]
I'm trying to capture the response and save it as a variable. Default streaming (text or all) results in only the first word being captured.

```
chat <- chat_gemini(
  model = "gemini-1.5-flash"
)
chat1.gemini1.5flash <- chat$chat(ch1)

chat1.gemini1.5flash
[1] "The"
```

But if I set echo to none then it is successfully captured:

```
chat <- chat_gemini(
  model = "gemini-1.5-flash",
  echo = "none" # echo text or all results in only the beginning of the response being captured
)
chat1.gemini1.5flash <- chat$chat(ch1)

> chat1.gemini1.5flash
[1] "The Moon doesn't have a capital city because it's not a country or a political entity with a government.  It's a natural satellite of Earth.\n"
```

Its only for gemini, no issue capturing the text for openai, claude, or llama

I was asked to add this - Joe says merge_dicts is not working correctly for Gemini, and Google’s implementation is [here](https://github.com/google-gemini/generative-ai-python/blob/b8772ed1424a080911151b354764d76a0e7af2af/google/generativeai/types/generation_types.py#L355-L372)

**Comment by jcheng5** [comment]
If you print the `chat1` object you'll also see that the message that's saved in the conversation history only includes the one "The" word. So this will also cause Gemini to have no idea what you're talking about in subsequent exchanges.

**Comment by jcheng5** [comment]
Thanks @leesahanders, so glad you caught this one!
