### ISSUE TITLE
`token_usage()` over-reports token usage

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/elmer#225]
Currently, `token_log()` [_adds_ together input + output tokens on every completion](https://github.com/tidyverse/elmer/blob/30b0f4a/R/tokens.R#L10), which leads `token_usage()` over-reporting the token usage.

This is because, the input/output tokens are logged, the input tokens represent the entire conversation history so far.

For a concrete example:

```r
library(elmer)
chat <- chat_openai()
chat$chat("Foo")
#> Hello! How can I assist you today?
chat$chat("Bar")
#> It looks like you’re playing with words a bit! How can I help you further?
chat$tokens()
```

Note how the last turn has the correct token usage for the conversation

```r
     input output
[1,]     0      0
[2,]     8      9
[3,]     0      0
[4,]    26     18
```

And `token_usage()` incorrectly reports the sums of each column.

```r
token_usage()
#>                                name input output
#> 1 OpenAI-https://api.openai.com/v1    34     27
```

**Comment by cpsievert** [comment]
Somewhat related to this, `chat$tokens()` doesn't feel very useful, since you mostly care about the tokens on the last turn.

So, instead of `chat$tokens()`, I think a `chat$token_usage()` (or similar) would be more helpful, and that would report the tokens attached to the last turn.

**Comment by jcheng5** [comment]
That looks correct to me? `token_usage()` reflects what you'll pay for, no?

**Comment by cpsievert** [comment]
Ahh yea, sorry for this.

Seems it would still be nice to have a way to more easily get at the most recent token usage (for checking/restricting the size of the conversation), but `chat$last_turn()@tokens` works for now
