### ISSUE TITLE
Explore databricks backend

### ISSUE THREAD

**Issue by hadley** [tidyverse/elmer#55]

**Comment by atheriel** [comment]
Databricks claims that [you can query their LLMs via the OpenAI client](https://docs.databricks.com/en/machine-learning/model-serving/score-foundation-models.html#language-OpenAI%C2%A0client), so this might be fairly easy to get working. The API parameter reference is messy but [can be found here](https://docs.databricks.com/api/workspace/servingendpoints/query).

We could also investigate how to list models or what would be available by default, too.

Auth stuff can probably be ported from `odbc` or `sparklyr`.

**Comment by zacdav-db** [comment]
[`chattr` supports Databricks via modifying the OpenAI support already](https://mlverse.github.io/chattr/articles/backend-databricks.html) - [It should be straightforward.](https://github.com/mlverse/chattr/blob/main/R/backend-databricks.R)

The models that are available by default can be queried via [API](https://docs.databricks.com/api/workspace/servingendpoints/list) with a filter for what chat/completion models the user has access to.

**Comment by hadley** [comment]
Ok great. Sounds like most of the work will be porting auth. I have a heavy meeting week this week, but hopefully I can squeeze it in soon.

**Comment by atheriel** [comment]
I can also try to take this on this week, since I'm familiar with both `elmer` internals and Databricks auth!
